version: '3.4'

services:
  sunoapi:
    image: xyfacai/sunoapi:latest
    container_name: sunoapi
    restart: always  
    network_mode: host
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./pprof:/pprof:rw
      - ./template:/template:rw
    environment:
      - PORT=8000
      - SQL_DSN=root:123456@tcp(localhost:3306)/sunoapi
      - TZ=Asia/Shanghai
      - ROTATE_LOGS=false
      - PPROF=false
      - DEBUG=false
      - TEMPLATE_DIR=./template
      - SUNO_CHAT_OPENAI_MODEL=gpt-4o
      - SUNO_CHAT_OPENAI_BASE=https://one-api.bltcy.top
      - SUNO_CHAT_OPENAI_KEY=sk-

networks:
  internal:      
